# Generated by Django 3.0.3 on 2020-02-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
