# Generated by Django 3.0.3 on 2020-02-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='versions',
            field=models.ManyToManyField(related_name='document_version_parent', to='repo.DocumentVersion'),
        ),
    ]
