# Generated by Django 3.0.3 on 2020-02-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20200221_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='versions',
            field=models.ManyToManyField(to='repo.DocumentVersion'),
        ),
    ]
